name: Build and Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    environment:
      name: cloudflare
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
 
      - name: Build site with SBCL
        run: nix run .#main-sbcl generate

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./out --project-name=tani-cc --commit-dirty=true
 
